# Generated by Django 6.0.1 on 2026-01-24 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='remedies.category')),
            ],
        ),
        migrations.CreateModel(
            name='Remedy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remedy_name', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('preparation_steps', models.TextField()),
                ('how_to_use', models.TextField()),
                ('frequency', models.CharField(max_length=100)),
                ('precautions', models.TextField()),
                ('why_it_works', models.TextField()),
                ('disclaimer', models.TextField(default='This remedy is for educational purposes only.')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remedies', to='remedies.problem')),
            ],
        ),
    ]
