# Generated by Django 6.0.1 on 2026-02-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='about_problem',
            field=models.TextField(default='Temporary data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='symptoms',
            field=models.TextField(default='Temporary data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='remedy',
            name='disclaimer',
            field=models.TextField(default='This remedy is for educational purposes only. Consult a healthcare professional if symptoms persist.'),
        ),
    ]
