# Generated by Django 6.0.1 on 2026-02-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remedies', '0003_remedy_lifestyle_tips_remedy_results_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remedy',
            name='disclaimer',
        ),
        migrations.RemoveField(
            model_name='remedy',
            name='frequency',
        ),
    ]
