# Generated by Django 6.0.1 on 2026-02-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedies', '0004_remove_remedy_disclaimer_remove_remedy_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='remedy',
            name='frequency',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='remedy',
            unique_together={('problem', 'remedy_name')},
        ),
    ]
