# Generated by Django 5.2.1 on 2026-03-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedies', '0005_remedy_frequency_alter_remedy_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
