# Generated by Django 5.2.1 on 2026-03-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remedies', '0007_userotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userotp',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='userotp',
            name='email',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
