# Generated by Django 5.2.1 on 2026-03-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remedies', '0008_remove_userotp_mobile_number_userotp_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
